services:
  - type: web_service
    name: credits-balance-presidency
    env: node
    branch: main
    buildCommand: "npm install"
    startCommand: "npm start"
    plan: free
    autoDeploy: true
    pullRequestPreviewsEnabled: false
    envVars:
      - key: ANTHROPIC_API_KEY
        value: ""
      - key: RENDER_AI_API_KEY
        value: ""
